### ISSUE TITLE
ground truth

### ISSUE THREAD

**Issue by HIT-Ygq** [joelloo/pharao_impl#3]
Hi, very great work, would you be willing to share the ground truth in your paper experiments? I would like to reproduce the experiments in your paper.

**Comment by joelloo** [comment]
Hello,

Thanks for your interest in this work! To clarify, I am not the original author of this work. As the original authors did not release their implementation, I decided to write my own implementation based on their description in the paper. As such, I do not have access to the exact results obtained by the original authors for PhaRaO.

However, I believe the original authors tested their work on the MulRan dataset, available [here](https://sites.google.com/view/mulran-pr/home). This dataset offers ground truth GPS trajectories together with NavTech radar images. I also used this dataset for my own personal tests of the code. Perhaps you can try to replicate their experiments using this dataset.

Hope you find this useful!

**Comment by HIT-Ygq** [comment]
Thanks!
